package com.bacen.regulatorio.openfinance.enums;

/**
 * Resolução BCB 32/2020 e atualizações — escopos de permissão do consentimento.
 * O usuário autoriza explicitamente cada permissão listada.
 */
public enum PermissaoConsentimento {
    // Fase 2 — leitura de dados cadastrais e transacionais
    CUSTOMERS_PERSONAL_IDENTIFICATIONS_READ,
    CUSTOMERS_PERSONAL_ADITTIONALINFO_READ,
    CUSTOMERS_BUSINESS_IDENTIFICATIONS_READ,
    CUSTOMERS_BUSINESS_ADITTIONALINFO_READ,

    // Contas
    ACCOUNTS_READ,
    ACCOUNTS_BALANCES_READ,
    ACCOUNTS_TRANSACTIONS_READ,
    ACCOUNTS_OVERDRAFT_LIMITS_READ,

    // Cartão de crédito
    CREDIT_CARDS_ACCOUNTS_READ,
    CREDIT_CARDS_ACCOUNTS_BILLS_READ,
    CREDIT_CARDS_ACCOUNTS_BILLS_TRANSACTIONS_READ,
    CREDIT_CARDS_ACCOUNTS_TRANSACTIONS_READ,
    CREDIT_CARDS_ACCOUNTS_LIMITS_READ,

    // Operações de crédito
    LOANS_READ,
    LOANS_WARRANTIES_READ,
    LOANS_SCHEDULED_INSTALMENTS_READ,
    LOANS_PAYMENTS_READ,

    FINANCINGS_READ,
    FINANCINGS_WARRANTIES_READ,
    FINANCINGS_SCHEDULED_INSTALMENTS_READ,
    FINANCINGS_PAYMENTS_READ,

    UNARRANGED_ACCOUNTS_OVERDRAFT_READ,
    UNARRANGED_ACCOUNTS_OVERDRAFT_WARRANTIES_READ,
    UNARRANGED_ACCOUNTS_OVERDRAFT_SCHEDULED_INSTALMENTS_READ,
    UNARRANGED_ACCOUNTS_OVERDRAFT_PAYMENTS_READ,

    INVOICE_FINANCINGS_READ,
    INVOICE_FINANCINGS_WARRANTIES_READ,
    INVOICE_FINANCINGS_SCHEDULED_INSTALMENTS_READ,
    INVOICE_FINANCINGS_PAYMENTS_READ,

    // Recursos disponíveis
    RESOURCES_READ,

    // Fase 3 — iniciação de pagamento
    PAYMENTS_INITIATE,

    // Fase 4 — seguros
    INSURANCE_PERSONAL_READ,
    INSURANCE_PERSONAL_AUTOMOBILE_READ,
    INSURANCE_PERSONAL_LIFE_READ,
    INSURANCE_PERSONAL_HOUSING_READ,
    INSURANCE_PERSONAL_TRAVEL_READ,
    INSURANCE_PERSONAL_CREDIT_READ,
    INSURANCE_PERSONAL_CARD_PROTECTION_READ,
    INSURANCE_BUSINESS_READ,
    INSURANCE_BUSINESS_LIABILITY_READ,
    INSURANCE_BUSINESS_CYBER_READ,
    INSURANCE_BUSINESS_CREDIT_READ,
    INSURANCE_BUSINESS_WARRANTY_READ,
    INSURANCE_BUSINESS_PEOPLE_READ,
    PENSION_PLAN_READ,
    PENSION_FUND_READ,
    PENSION_FUND_UPDATE,

    // Fase 4 — investimentos
    INVESTMENTS_STOCK_READ,
    INVESTMENTS_FIXED_INCOME_READ,
    INVESTMENTS_FUNDS_READ,
    INVESTMENTS_VARIABLE_INCOME_READ,
    INVESTMENTS_TREASURY_READ,
    INVESTMENTS_DERIVATIVES_READ,
    INVESTMENTS_ETF_READ,
    INVESTMENTS_COIN_READ,
    INVESTMENTS_REAL_ESTATE_READ,
    INVESTMENTS_STRUCTURED_READ,

    // Fase 4 — câmbio
    EXCHANGE_TRANSACTION_READ,
    EXCHANGE_OPERATION_READ,
    EXCHANGE_LIMITS_READ,

    // Fase 4 — previdência complementar aberta
    PENSION_OPEN_ENTITY_READ,
    PENSION_OPEN_ENTITY_PORTABILITY_READ
}
